spring.application.name=backend_tings
app.security.bcrypt.strength=12
jwt.secret=${JWT_SECRET}
refresh.secret=${REFRESH_SECRET}
database.url=${DATABASE_URL}
google.app.password=${GOOGLE_APP_PASSWORD}
upstash.redis.rest.url=${UPSTASH_REDIS_REST_URL}
upstash.redis.rest.token=${UPSTASH_REDIS_REST_TOKEN}
kv.url=${KV_URL}
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
client.id=${CLIENT_ID}
client.secret=${CLIENT_SECRET}
gemini.api.key=${GEMINI_API_KEY}
blob.read.write.token=${BLOB_READ_WRITE_TOKEN}
stripe.price.pro.yearly=${STRIPE_PRICE_PRO_YEARLY}
stripe.price.enterprise.yearly=${STRIPE_PRICE_ENTERPRISE_YEARLY}
